Algoritmo "SOMADOR_NUMERICO"

Var
   contador,N: Inteiro


Inicio

   //Inicio da contagem em 1

   contador <- 1

   Enquanto (contador <= 10) faca

      // Interação do usuário

      EscrevaL("Digite o valor que você gostaria de contar?")
      Leia (N)
      contador <- contador + 1

      // A cada número informado, o programa irá refazer essa pergunta 10 vezes.


   FimEnquanto

   Escreval ("Terminei de contar!")

Fimalgoritmo